version: '2'

networks:
  fcwmp:
  honeyc:
  public:
  genie:


services:

  freecwmp:
    build: freecwmp
    depends_on:
      - sensor-freecwmp
    networks:
      - fcwmp

  honeyclient:
    build: ../honeyclient
    depends_on:
      - sensor-honeyclient
    networks:
      - honeyc

  sensor-honeyclient:
    build:
      context: ../monitor
      dockerfile: Dockerfile-sensor
    ports:
      - "8081:8081"
    expose:
      - 7547
    depends_on:
      - genieacs-cwmp
      - collector
    volumes:
      - ./certs/cert.crt:/opt/ca-certs
    environment:
      REQUESTS_CA_BUNDLE: /opt/ca-certs
    networks:
      honeyc:
        aliases:
         - acs
      public:


  sensor-freecwmp:
    build:
      context: ../monitor
      dockerfile: Dockerfile-sensor
    ports:
      - "8082:8081"
    expose:
      - 7547
    depends_on:
      - genieacs-cwmp
      - collector
    volumes:
      - ./certs/cert.crt:/opt/ca-certs
    environment:
      REQUESTS_CA_BUNDLE: /opt/ca-certs
    networks:
      fcwmp:
        aliases:
         - acs
      public:


  collector:
    build:
      context: ../monitor
      dockerfile: Dockerfile-collector
    expose:
      - 443
    volumes:
      - ./certs/cert.crt:/usr/src/tr069monitor/cert.crt
      - ./certs/cert.key:/usr/src/tr069monitor/cert.key
      - .:/usr/src/tr069monitor/data
    networks:
      public:
        aliases:
         - collector

  #openacs:
  #  build: openacs
  #  ports:
  #   - "8547:8080"

  mongodata:
    image: mongo:3.2
    volumes:
      - /data/db
    command: --break-mongo

  mongo:
    image: mongo:3.2
    volumes_from:
      - mongodata
    expose:
      - 27017
    networks:
     - genie

  redis:
    image: redis:2.8
    expose:
      - 6379
    networks:
     - genie

  # this is here so that the base image is built.
  genieacs-base:
    build: genieacs-base
    image: genieacs-base
    volumes:
      - /data/db
    command: "true"

  genieacs-cwmp:
    build: genieacs-cwmp
    depends_on:
      - genieacs-fs
    links:
      - mongo
      - redis
    ports:
      - "7547:7547"
    networks:
      public:
        aliases:
         - genieacs
      genie:

  genieacs-nbi:
    build: genieacs-nbi
    links:
      - mongo
      - redis
    ports:
      - "7557:7557"
    networks:
     - genie

  genieacs-fs:
    build: genieacs-fs
    links:
      - mongo
      - redis
    ports:
      - "7567:7567"
    networks:
     - genie

  genieacs-gui:
    build: genieacs-gui
    links:
      - genieacs-nbi
    ports:
      - "3000:3000"
    networks:
     - genie
